spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: create-drop
  datasource:
    url: jdbc:h2:mem:comprasdb
server:
  port: 8089
logging:
  level: debug